### ISSUE TITLE
[Doc] Documentation should be added for the new improvement of supporting OAuth 2.0 endpoint security via params file

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#786]
**Description:**
The documentation in [1] for 3.2.0 and [2] for master should be updated for the new improvement of supporting OAuth 2.0 endpoint security via params file done when fixing [3] and [4].

**Todo**
- [ ] Update the documentation in [1] and [2]
- [ ] Create a separate section or a page to explain the difference between setting up digest and basic and OAuth 2.0 endpoint security using the params file. 
- [ ] Make sure to highlight that in digest and basic, we can only set up the security globally but in OAuth 2.0 we can support for Production and Sandbox endpoints separately
- [ ] Include the supported WUM/U2 version which this improvement has been done.

**Affected Product Version:**
APICTL 3.2.x
Master

**Related Issues:**
- https://github.com/wso2/product-apim-tooling/issues/784
- https://github.com/wso2/product-apim-tooling/issues/785

[1] https://apim.docs.wso2.com/en/3.2.0/learn/api-controller/advanced-topics/configuring-environment-specific-parameters/#configuring-environment-specific-parameters
[2] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters/
[3] https://github.com/wso2/product-apim-tooling/issues/784
[4] https://github.com/wso2/product-apim-tooling/issues/785
