### ISSUE TITLE
CLI Support for the Per Logging API Feature 

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#872]
### Describe your problem(s)
API needs to be debugged at run-time with the logs. APIs should be able to log details such as the headers and body content that comes into and goes out from the APIM. This would help to debug and analyze the issues in requests and transformation(mediation) flows at the run-time for a given API. For each API, there should be a way to configure/set and view the log levels(header/body) and the logs using a CLI.

### Describe your solution
Add commands to configure/set and view the log levels(header/body) and the logs for each API using the APICTL.

### How will you implement it
The following list of commands will be implemented to support per API logging feature related operations.

#### Get API List
Provides a list of logging enabled APIs with relevant log levels. You will get all the APIs in a given environment with the available log levels when the api-id is not provided and you will get the specific log level details of an API when the api-id is provided.

##### Command
apictl get api-logging --environment \<environment\>
apictl get api-logging --environment \<environment\> –tenant-domain \<tenant domain\>
apictl get api-logging  --environment \<environment\> --api-id \<api-id\>
apictl get api-logging  --environment \<environment\> --api-id \<api-id\> –tenant-domain \<tenant domain\>
##### Response
The response sends a list  of the APIs  along with the corresponding log level.

```
API_ID 	                              API_CONTEXT	        LOG_LEVEL
Bf36ca3a-0332-49ba-abce-e9992228ae06  pizzashack/1.0.0	        FULL
Af66fa7a-0546-49ba-adfe-a8976522ea96  sampleapi/1.1.0	        BASIC
```

#### Add/Change/Remove Logging for an API
This command lets you add a new per API logger with the given log level or change/remove a log level assigned for an API. API ID  and the log level should be provided as the flags in addition to the environment where the API is deployed.

When you need to disable logging for an API, set the log level to OFF.

##### Command
apictl set api-logging --api-id \<api-id\> --log-level full --environment \<environment\>
apictl set api-logging --api-id \<api-id\> --log-level full --environment \<environment\> –tenant-domain \<tenant domain\>
##### Response
Log level FULL is successfully set to the API.

For both the above commands, tenant-domain flag is optional and carbon.super will be used as the default value if the flag is not provided.

---
#### Related Issues:
https://github.com/wso2/product-apim/issues/11720

- [x] Add Implementation for the get and set commmands - https://github.com/wso2/product-apim-tooling/issues/872
- [x] Add relevant documentation changes - https://github.com/wso2/product-apim-tooling/issues/866
- [ ] Add an integration test for the CTL side - https://github.com/wso2/product-apim-tooling/issues/867

**Comment by wasuradananjith** [comment]
Implementation done via https://github.com/wso2/product-apim-tooling/issues/872. Hence, closing the issue.

**Comment by npamudika** [comment]
Original Issue - https://github.com/wso2/product-apim/issues/12098
